version: '3'

networks:
  backend:
  frontend:

services:
  ### node #########################################
  nextjs:
    container_name: nextjs-let-it-ride
    networks:
      - frontend
      - backend
    restart: always
    image: node:18.5.0
    ports:
      - "80:3000"
    working_dir: '/usr/src/nextjs/'
    command: "npm run dev"
    volumes:
      - ../:/usr/src/nextjs

  ### redis #########################################
  redis:
    container_name: redis
    networks:
      - backend
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"